---
name: 'Issue with ketting (NOT THE LAUNCHER)'
description: 'Wrong repository!'
title: 'I don't like reading!'
labels: 'bug'
#assignees: ''

---

Please report ketting related bugs at https://github.com/kettingpowered/Ketting-1-20-x/issues not here
