name: 'Issue with ketting (NOT THE LAUNCHER)'
description: 'Wrong repository!'
title: 'I don't like reading!'
labels: 'bug'
#assignees: ''
body:
  - type: textarea
    attributes:
      label: 'Reasoning'
      description: 'Why you don't wanna go to the proper repository to report your bug'
    validations:
      required: true
---
Please report ketting related bugs at https://github.com/kettingpowered/Ketting-1-20-x/issues not here
---
